// Generate every static brand asset from the one shared geometry source (src/shell/brandMarkGeometry.ts),
// so the favicon, the installed-app tile, and the link-preview card can never drift from the in-app mark.
// Run with `npm run generate:brand` (or `node scripts/generate-brand-assets.ts`).
//
//   - SVGs are written straight from the geometry: public/favicon.svg, public/brand/icon-maskable.svg,
//     public/og-image.svg. Pure, no external tools.
//   - PNGs are rasterised from those SVGs with headless Chrome: the maskable tile to public/icons/icon-192.png,
//     icon-512.png and public/apple-touch-icon.png, and the card to public/og-image.png. Skipped with a notice
//     when no Chrome binary is found (set CHROME_BIN to point at one).
import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { BRAND_COLORS, brandMarkGeometry, type BrandMarkGeometry } from "../src/shell/brandMarkGeometry.ts";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const round = (v: number): number => {
  const r = Math.round(v * 1000) / 1000;

  return Object.is(r, -0) ? 0 : r;
};

// The mark's three elements (court boundary, attack line, ball) in `frame` coordinates. `court` is the
// attribute that colours the boundary and attack line: a literal stroke for a baked surface, or a CSS class
// for the theme-aware favicon.
function markElements(g: BrandMarkGeometry, court: string, ball: string, indent = "  "): string {
  return [
    `<rect ${court} fill="none" x="${round(g.court.x)}" y="${round(g.court.y)}" width="${round(g.court.size)}" height="${round(g.court.size)}" rx="${round(g.court.radius)}" stroke-width="${round(g.court.strokeWidth)}" />`,
    `<line ${court} x1="${round(g.attackLine.x1)}" y1="${round(g.attackLine.y1)}" x2="${round(g.attackLine.x2)}" y2="${round(g.attackLine.y2)}" stroke-width="${round(g.attackLine.strokeWidth)}" />`,
    `<circle fill="${ball}" cx="${round(g.ball.cx)}" cy="${round(g.ball.cy)}" r="${round(g.ball.radius)}" />`,
  ].join(`\n${indent}`);
}

// The browser-tab icon: the mark on transparency, maximised to all four edges, its court swapping with the
// browser's light/dark chrome through a prefers-color-scheme rule. The amber ball is constant.
export function faviconSvg(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100" role="img" aria-label="VolleyCoach">
  <!-- Generated by scripts/generate-brand-assets.ts. The court swaps with browser chrome; the amber ball is constant. -->
  <style>
    .court { stroke: ${BRAND_COLORS.charcoal}; }
    @media (prefers-color-scheme: dark) { .court { stroke: ${BRAND_COLORS.offWhite}; } }
  </style>
  ${markElements(brandMarkGeometry(100), 'class="court"', BRAND_COLORS.ball)}
</svg>
`;
}

// The installed-app icon: a full-bleed warm charcoal tile (the OS applies its own mask shape) with the mark
// pulled inside the maskable safe zone, baked to the warm expression since a raster cannot follow the theme.
export function maskableSvg(px = 100): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="${px}" height="${px}" role="img" aria-label="VolleyCoach">
  <!-- Generated by scripts/generate-brand-assets.ts. Full-bleed maskable tile; the OS applies its own mask. -->
  <rect x="0" y="0" width="100" height="100" fill="${BRAND_COLORS.charcoal}" />
  ${markElements(brandMarkGeometry(100, { masked: true }), `stroke="${BRAND_COLORS.offWhite}"`, BRAND_COLORS.ball)}
</svg>
`;
}

// The link-preview card: the mark beside the wordmark, centred on the warm charcoal field.
export function ogSvg(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630" width="1200" height="630" role="img" aria-label="VolleyCoach">
  <!-- Generated by scripts/generate-brand-assets.ts. Re-rasterise og-image.png from this (the font loads from Google Fonts). -->
  <style>
    @import url("https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:wght@800&amp;display=swap");
    .word {
      font-family: "Bricolage Grotesque", system-ui, sans-serif;
      font-weight: 800;
      font-size: 132px;
      letter-spacing: -0.035em;
      fill: ${BRAND_COLORS.offWhite};
    }
  </style>
  <defs>
    <radialGradient id="field-glow" cx="50%" cy="-8%" r="75%">
      <stop offset="0%" stop-color="#ffffff" stop-opacity="0.14" />
      <stop offset="60%" stop-color="#ffffff" stop-opacity="0" />
    </radialGradient>
  </defs>
  <rect width="1200" height="630" fill="${BRAND_COLORS.charcoal}" />
  <rect width="1200" height="630" fill="url(#field-glow)" />
  <svg x="121" y="239" width="152" height="152" viewBox="0 0 152 152">
    ${markElements(brandMarkGeometry(152), `stroke="${BRAND_COLORS.offWhite}"`, BRAND_COLORS.ball, "    ")}
  </svg>
  <text x="323" y="315" class="word" dominant-baseline="central">VolleyCoach</text>
</svg>
`;
}

function findChrome(): string | null {
  const candidates = [process.env.CHROME_BIN, "google-chrome", "google-chrome-stable", "chromium", "chromium-browser"];

  for (const bin of candidates) {
    if (!bin) continue;
    try {
      execFileSync(bin, ["--version"], { stdio: "ignore" });

      return bin;
    } catch {
      // try the next candidate
    }
  }

  return null;
}

// Rasterise an SVG document to a PNG at its intrinsic width/height with headless Chrome.
function rasterize(chrome: string, tmp: string, name: string, svg: string, out: string, w: number, h: number): void {
  const src = join(tmp, `${name}.svg`);

  writeFileSync(src, svg);
  execFileSync(chrome, [
    "--headless",
    "--disable-gpu",
    "--no-sandbox",
    "--hide-scrollbars",
    "--force-color-profile=srgb",
    "--default-background-color=00000000",
    "--virtual-time-budget=10000",
    `--screenshot=${out}`,
    `--window-size=${w},${h}`,
    `file://${src}`,
  ]);
}

function main(): void {
  writeFileSync(join(ROOT, "public/favicon.svg"), faviconSvg());
  writeFileSync(join(ROOT, "public/brand/icon-maskable.svg"), maskableSvg());
  writeFileSync(join(ROOT, "public/og-image.svg"), ogSvg());
  console.log("Wrote favicon.svg, brand/icon-maskable.svg, og-image.svg");

  const chrome = findChrome();

  if (!chrome) {
    console.warn("No Chrome binary found (set CHROME_BIN); skipped PNGs. Rasterise the SVGs above by hand.");

    return;
  }

  const pngs: { out: string; svg: string; w: number; h: number }[] = [
    { out: "public/icons/icon-192.png", svg: maskableSvg(192), w: 192, h: 192 },
    { out: "public/icons/icon-512.png", svg: maskableSvg(512), w: 512, h: 512 },
    { out: "public/apple-touch-icon.png", svg: maskableSvg(180), w: 180, h: 180 },
    { out: "public/og-image.png", svg: ogSvg(), w: 1200, h: 630 },
  ];
  const tmp = mkdtempSync(join(tmpdir(), "brand-"));

  try {
    pngs.forEach((p, i) => rasterize(chrome, tmp, `png${i}`, p.svg, join(ROOT, p.out), p.w, p.h));
    console.log(`Rasterised ${pngs.length} PNGs from the SVG sources`);
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }

  for (const p of pngs) {
    if (!existsSync(join(ROOT, p.out))) throw new Error(`Expected ${p.out} to be written`);
  }
}

// Run the generator only when invoked as a script; the drift test imports the SVG builders above.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
